#!/usr/bin/env python3
"""Build Android prompt lexicon assets from wordfreq and CMUdict."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import cmudict
from wordfreq import top_n_list


WORD_RE = re.compile(r"^[a-z]{2,12}$")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=Path("android/app/src/main/assets"))
    parser.add_argument("--word-count", type=int, default=20_000)
    parser.add_argument("--phone-word-count", type=int, default=50_000)
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    ranked_words = [word for word in top_n_list("en", args.phone_word_count * 2) if WORD_RE.match(word)]
    prompt_words = ranked_words[: args.word_count]
    phone_words = set(ranked_words[: args.phone_word_count])

    phones_by_word: dict[str, list[str]] = {}
    for word, phones in cmudict.entries():
        normalized = word.lower()
        if normalized in phone_words and normalized not in phones_by_word:
            phones_by_word[normalized] = phones

    (args.out / "prompt_words.txt").write_text(
        "# Generated by scripts/build_prompt_lexicon.py from wordfreq.\n"
        "# Source: https://pypi.org/project/wordfreq/\n"
        + "\n".join(prompt_words)
        + "\n",
        encoding="utf-8",
    )

    (args.out / "cmudict_phones.tsv").write_text(
        "# Generated by scripts/build_prompt_lexicon.py from CMUdict.\n"
        "# Source: https://www.speech.cs.cmu.edu/cgi-bin/cmudict\n"
        + "\n".join(
            f"{word}\t{' '.join(phones)}"
            for word, phones in sorted(phones_by_word.items())
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
